### PR TITLE
PHPORM-90 Fix whereNot to use `$nor`

### LINKED ISSUE #2623: Error executing whereNot
- Laravel-mongodb Version: 4.0.0-rc1
- PHP Version: 9.1
- Database Driver & Version: 6.0.4

### Description:
Executing whereNot query throws error: `unknown top level operator: $not. If you are trying to negate an entire expression, use $nor.`

### PR DESCRIPTION
**Pull request by GromNaN**
Fix #2623 #2418 [PHPORM-90](https://jira.mongodb.org/browse/PHPORM-90)

[`$not`](https://www.mongodb.com/docs/manual/reference/operator/query/not/) cannot be used with an expression. I switched to [`$nor`](https://www.mongodb.com/docs/manual/reference/operator/query/nor/), that negates a list of expressions.

The query could be optimized, but I expect the mongo server to be smart enough to do it.

Example of optimization I chose not to do because that would require to detect when there is a single field expression (related to https://github.com/GromNaN/laravel-mongodb/pull/13#discussion_r1268289478)

This expression:
```ts
{ field: { operator: value } }
```

Is negated with:
```ts
{ $nor: [ { field: { operator: value } } ] }
```
While it could also be:
```ts
{ field: { $not: { operator: value } }
```

### CODE REVIEW

File: src/Query/Builder.php [hunk 1]
```diff
@@ -1053,8 +1053,9 @@ protected function compileWheres(): array
             $method = 'compileWhere' . $where['type'];
             $result = $this->{$method}($where);
 
+            // Negate the expression
             if (str_ends_with($where['boolean'], 'not')) {
-                $result = ['$not' => $result];
+                $result = ['$nor' => [$result]];
```
Comment (jmikola) [inline src/Query/Builder.php:1058]: I don't see [PHPORM-90](https://jira.mongodb.org/browse/PHPORM-90) linked to anything. This this bug predate us taking over the library, or was it introduced during some recent query refactoring? If the latter, we should link it up.

File: src/Query/Builder.php [hunk 2]
```diff
@@ -1053,8 +1053,9 @@ protected function compileWheres(): array
             $method = 'compileWhere' . $where['type'];
             $result = $this->{$method}($where);
 
+            // Negate the expression
```
Comment (jmikola) [inline src/Query/Builder.php:1056]: Is `$result` always going to be an `<expression>` at this point, and never an `<operator-expression>` as it expected by [$not](https://www.mongodb.com/docs/manual/reference/operator/query/not/)?

This is related to my other comment, in that I'm curious how this wasn't discovered sooner unless it was only recently introduced.

File: tests/QueryTest.php [hunk 3]
```diff
@@ -154,6 +156,43 @@ public function testSelect(): void
         $this->assertNull($user->age);
     }
 
+    public function testWhereNot(): void
+    {
+        // implicit equality operator
+        $users = User::whereNot('title', 'admin')->get();
+        $this->assertCount(6, $users);
```
Comment (GromNaN) [inline tests/QueryTest.php:163]: This test is failing if I run it on version 3.9.3: the generated query was `{ title: 'admin' }`, which is wrong because it ignore the negation.
In the current master, the query is `{ $not: { title: 'admin' } }`, which is invalid and rejected by the server.
With this patch, the working query is `{ $nor: [ { title: 'admin' } ] }`.

File: src/Query/Builder.php (hunk 2 above)
Comment (GromNaN) [reply src/Query/Builder.php:1056]: Yes, `compileWhere*` function always return expressions with `$and`, `$or` or a field name, and now `$nor`.

File: src/Query/Builder.php (hunk 1 above)
Comment (GromNaN) [reply src/Query/Builder.php:1058]: I implemented `whereNot` in https://github.com/GromNaN/laravel-mongodb/pull/13. The issue [PHPORM-49](https://jira.mongodb.org/browse/PHPORM-49) is now linked in Jira.

File: tests/QueryTest.php (hunk 3 above)
Comment (jmikola) [reply tests/QueryTest.php:163]: >  reviewing the generated query was { title: 'admin' }, which is wrong because it ignore the negation.

I'm not sure if I realized this when originally reviewing [PHPORM-49](https://jira.mongodb.org/browse/PHPORM-49), but the fact that earlier versions completely ignored negations with no feedback to the user sounds like pretty disastrous bug.
